### ISSUE TITLE
HMAC doesn't validate with current loadtest.py script + HMAC_KEY against https://stubattribution-default.stage.mozaws.net/

### ISSUE THREAD

**Issue by stephendonner** [stephendonner/stubattribution-loadtests#4]
Running https://github.com/stephendonner/stubattribution-loadtests/blob/97d033071cf08b73d5af84ed49aef7d530c9fa00/loadtest.py against https://stubattribution-default.stage.mozaws.net/ as follows:

```
molotov -cx -d 1 loadtest.py
```
yields:

```
**** Molotov v0.2. Happy breaking! ****
[30818] Preparing 1 workers...OK
..
2 OK, 0 Failed
```

However, we see the following HMAC validation exception thrown, in Sentry:

https://sentry.prod.mozaws.net/operations/stub_attribution-stage/issues/379693/

```
could not validate attribution_code: source%3D(not+set)%26medium%3Dbac72540-45d6-4698-a0b7-63a00adcbea3%26campaign%3D(not+set)%26content%3D(not+set)%26timestamp%3D1485414893: HMAC would not validate. given: 87789e4c3815345752a686d323c476f9350f0d16f919e3ee7b2858c19b4ae07a expected: ca365c22665a271e1bf50eb9350d9cac15c499fcf8853e73e6e841f80c35ad4b
```

**Comment by pmac** [comment]
Hmm... Let me double check the hmac key I gave you.

**Comment by stephendonner** [comment]
Sorry, I believe this was due to https://github.com/loads/molotov/issues/18.  Anyway, works for me, now.
